### PR TITLE
Bugfix in case of missing from field from CallbackQuery

### PR DESCRIPTION
**Pull request by Emulator000**
Implemented a different type of Message only for CallbackQuery. Sometimes it will fail if the field missing.

### CODE REVIEW

**Comment by knsd** [comment]
Hi, Emulator000. Can you please clarify your changes? How does this Message differs from existing Message?

**Comment by Emulator000** [comment]
This message have an optional from, due to this: "Message with the callback button that originated the query. Note that message content and message date will not be available if the message is too old"

In some occasion my bot displayed a JSON error on the message saying that from doesn't exists and was stuck in a crash loop.

**Comment by shouya** [comment]
Do you mean that the message field in a callback may be optional? This way shouldn't we changing the `message` field in `CallbackQuery` to type `Option<Message>`?

Note that doing this will break backward compatibility, so be careful.

**Comment by Emulator000** [comment]
@shouya I think you are absolutely right, sorry for being a little unclear.

I just commited again with a more concise fix regarding this issue, in my test cases, the issue was only on the "from" field that on the "from_raw_message" was returning this error.

**Comment by knsd** [comment]
First of all, thanks for your report.

Is it about `CallbackQuery` for channel posts by any chance? Looks like we should use `MessageOrChannelPost` instead of `Message` in `CallbackQuery.message` field. It will break backward compatibility, but I think it's better than implicitly set zero `User` in a `from` field because no one will check it.

However, I still don't know what to do with «Note that message content and message date will not be available if the message is too old», I can't reproduce it, but it could be a very annoying deserialization error.

**Comment by Emulator000** [comment]
@knsd I have some log with the bot keeping failing with this error in a loop, sometimes Telegram (maybe undocumented!) sends a bad Message with missing fields (in this case, only the "from" field, nothing related on what the note says).

We could implement another type of Message breaking the compatibility but I think is necessary.

Try for example to add a button and wait 1 day or less (I don't remember) then click to this button and the bot will not expect that the "from" field from the Message struct missing.

With my fix (temporary fix) will not break anything, just not throw an error in case this field is not present.

**Comment by shouya** [comment]
I like it if we stop worrying about backward compatibility. In fact, I'm not sure why we need an extra channel post struct when it only differs from Message with a single field, given even telegram documentation describes them as a single type.

I personally would prefer dropping `CallbackQuery` and leaving only one `Message` type with an optional `from` field. Making them a single type will make it easier to write functions that handles both channel post and messages, which actually are very alike. What do you think?

**Comment by knsd** [comment]
> Making them a single type will make it easier to write functions that handles both channel post and messages, which actually are very alike in structure.

Good point, guess we should do it.

**Pull request closed without merging**
