### PR TITLE
Add useful traits to easily get text or file properties from messages

### LINKED ISSUE #144: Trait to get text body for any message kind
A while back I implemented a trait to get the text body for any message kind (along with some other ones), to prevent implementing huge `match` statements throughout the code.

Would it be useful to implement something like this in the core `telegram-bot` crate? If so, I can take this task on me.

Example implementation:
https://github.com/timvisee/risc-bot/blob/10905c5efa9a8067ac202db93f28dc1a6e2c8f6e/src/traits.rs#L3-L60

### PR DESCRIPTION
**Pull request by timvisee**
Fixes #144 

This implements the `MessageText` and `MessageGetFiles` traits to easily get text and file components from any message kind using `text()` and `get_files()`.

These traits have been implemented in a new `traits.rs` module, and are included in the prelude.
Please let me know if a different location, or different naming is desired.

Both traits currently return owned types, as I don't see a nice way of returning references for every type.

### CODE REVIEW

**Comment by gugahoa** [comment]
I'm not quite sure where I would put that trait too, as it's more of a utility trait than anything else. My first thought would be that it should go in https://github.com/telegram-rs/telegram-bot/blob/master/raw/src/types/message.rs as it's a trait related to messages' types and that others could benefit from it being in the `telegram-bot-raw` crate instead of `telegram-bot` crate.

What do you think?

**Comment by timvisee** [comment]
I thought the `-raw` create was just for core types, so `Message` is in there because it's a core Telegram API thing, which the bot can't live without.

I didn't consider the traits I've added to be such a 'core' thing, and more of a utility/extension like you're saying.

By that logic; what about moving it to something like `lib/util/message.rs`?

**Comment by gugahoa** [comment]
Sounds good to me

**Comment by timvisee** [comment]
Bump. Just to notify you that these traits have now been moved.

**Comment by gugahoa** [comment]
Thanks for the contribution!

**Pull request merged**
