### PR TITLE
Add Dependabot config

### PR DESCRIPTION
**Pull request by red-avtovo**
Updated dependencies: tokio, hyper, hyper-tls
Added Dependobot config

### CODE REVIEW

**Comment by bemyak** [comment]
Seems like a duplicate of https://github.com/telegram-rs/telegram-bot/pull/228

**Comment by red-avtovo** [comment]
@bemyak oh, wow indeed. Thx for taking a look on it. I will filter everything that was fixed by #228 and push updates soon. Basically only dependabot config will stay

**Comment by red-avtovo** [comment]
@knsd any objections on that change?

**Review by gugahoa — APPROVED** [review]

**Comment by gugahoa** [comment]
Thanks!

**Pull request merged**
